#!/bin/bash

SCRIPTS_DIR=$(dirname $0)/..

set -o errexit

BRANCH_NAME=${BRANCH_NAME:-$WERCKER_GIT_BRANCH}

OPTIONS=$($SCRIPTS_DIR/test-instance/get-options)
OPTIONS="--branch-name $BRANCH_NAME $OPTIONS"
$SCRIPTS_DIR/test-instance/launch $OPTIONS
